version: "3.9"

services:
  postgres-db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: crediya_requests
    ports:
      - "5433:5433"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
